{% set name = "pyfolio-reloaded" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfolio-reloaded-{{ version }}.tar.gz
  sha256: e30d0631502ea57ed2e5f35fb0e50b1f5a779f9f67d5947d95cd5b746c3a03c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ipython >=3.2.3
    - matplotlib-base >=1.4.0
    - numpy >=1.11.1
    - pandas >=0.18.1
    - pytz >=2014.10
    - scipy >=0.14.0
    - scikit-learn >=0.16.1
    - seaborn >=0.7.1
    - empyrical-reloaded >=0.5.8

test:
  imports:
    - pyfolio
  source_files:
    - tests
  commands:
    - pytest --ignore tests/test_timeseries.py tests/
  requires:
    - coverage >=4.0.3
    - coveralls ==3.0.1
    - pytest >=6.2
    - pytest-xdist >=2.5.0
    - pytest-cov >=2.12
    - parameterized >=0.6.1

about:
  home: https://pypi.org/project/pyfolio-reloaded/
  summary: Performance and risk analysis of financial portfolios with Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefan-jansen
